<a href="https://colab.research.google.com/github/Mallowsss/CCDATSCL_EXERCISES/blob/main/Exercise3_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 3

<img src="https://img.itch.zone/aW1nLzM0MzUxOTUuanBn/original/FuMxog.jpg" />

In this exercise, you will perform EDA on the popular Pokémon dataset, which contains detailed information about hundreds of Pokémon, including their stats, types, generation, and whether they are legendary.

The Pokémon dataset is ideal for practicing EDA because it includes a mix of numerical features (such as Attack, Defense, Speed, HP) and categorical features (such as Type 1, Type 2, and Generation). This combination allows you to apply a wide range of EDA techniques, including summary statistics, data visualizations, grouping and aggregation, correlation analysis, and comparisons across categories.

Throughout the exercise, you will explore questions such as:
- Which Pokémon tend to have the highest or lowest stats?
- How do different Pokémon types compare in terms of strength or defense?
- Do Legendary Pokémon differ significantly from non-Legendary ones?
- How are various stats distributed across the entire dataset?
- Are there relationships or trade-offs between certain attributes (e.g., Attack vs. Defense)?

In [1]:
import kagglehub
import os
import pandas as pd

In [2]:
# Download latest version
path = kagglehub.dataset_download("abcsds/pokemon")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pokemon' dataset.
Path to dataset files: /kaggle/input/pokemon

In [3]:
if os.path.isdir(path):
  print(True)

contents = os.listdir(path)
contents

mydataset = path + "/" + contents[0]
mydataset


df = pd.read_csv(mydataset)

True


## 1: Data Understanding (4 pts)

1. Display the first 10 rows.

In [4]:
# put your answer here
df.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

2. Show dataset shape.

In [5]:
# put your answer here
df.shape

(800, 13)

3. Show all columns and its data types.

In [6]:
# put your answer here
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

4. Identify which columns contain missing values.

In [7]:
# put your answer here
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

## 2. Summary Statistics (4 pts)

1. Generate `df.describe()`.

In [8]:
# put your answer here
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

2. Get mean, median, and mode of Attack.

In [12]:
# put your answer here
print(f"Attack's Mean: {df.Attack.mean()}")
print(f"Attack's Median: {df.Attack.median()}")
print(f"Attack's Mode: {df.Attack.mode()}")

Attack's Mean: 79.00125
Attack's Median: 75.0
Attack's Mode: 0    100
Name: Attack, dtype: int64

3. Compute 25th and 75th percentiles for HP.

In [14]:
# put your answer here
print(f"HP's 25th Percentile: {df.HP.quantile(0.25)}")
print(f"HP's 75th Percentile: {df.HP.quantile(0.75)}")

HP's 25th Percentile: 50.0
HP's 75th Percentile: 80.0

4. Compute standard deviation and variance of Speed.

In [15]:
# put your answer here
print(f"Speed's Standard Deviation: {df.Speed.std()}")
print(f"Speed's Variance: {df.Speed.var()}")

Speed's Standard Deviation: 29.06047371716149
Speed's Variance: 844.5111326658338

## 3. Filtering & Selection `(7 pts)`

Select all Pokémon with Attack > 100.

In [16]:
# put your answer here
df[df.Attack > 100]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Select all Pokémon whose primary type (Type 1) is "Fire".

In [22]:
# put your answer here
df.loc[df["Type 1"] == "Fire", ["Name", "Type 1"]]

                          Name Type 1
4                   Charmander   Fire
5                   Charmeleon   Fire
6                    Charizard   Fire
7    CharizardMega Charizard X   Fire
8    CharizardMega Charizard Y   Fire
42                      Vulpix   Fire
43                   Ninetales   Fire
63                   Growlithe   Fire
64                    Arcanine   Fire
83                      Ponyta   Fire
84                    Rapidash   Fire
135                     Magmar   Fire
147                    Flareon   Fire
158                    Moltres   Fire
169                  Cyndaquil   Fire
170                    Quilava   Fire
171                 Typhlosion   Fire
236                     Slugma   Fire
237                   Magcargo   Fire
259                      Magby   Fire
263                      Entei   Fire
270                      Ho-oh   Fire
276                    Torchic   Fire
277                  Combusken   Fire
278                   Blaziken   Fire
279      BlazikenMega Blaziken   Fire
352                      Numel   Fire
353                   Camerupt   Fire
354      CameruptMega Camerupt   Fire
355                    Torkoal   Fire
435                   Chimchar   Fire
436                   Monferno   Fire
437                  Infernape   Fire
518                  Magmortar   Fire
542                    Heatran   Fire
557                      Tepig   Fire
558                    Pignite   Fire
559                     Emboar   Fire
572                    Pansear   Fire
573                   Simisear   Fire
614                   Darumaka   Fire
615    DarmanitanStandard Mode   Fire
616         DarmanitanZen Mode   Fire
692                    Heatmor   Fire
721                   Fennekin   Fire
722                    Braixen   Fire
723                    Delphox   Fire
730                Fletchinder   Fire
731                 Talonflame   Fire
735                     Litleo   Fire
736                     Pyroar   Fire
799                  Volcanion   Fire

Select all Pokémon that are Legendary.

In [39]:
# put your answer here
df.loc[df["Legendary"] == True, ["Name", "Legendary"]]

                    Name  Legendary
156             Articuno       True
157               Zapdos       True
158              Moltres       True
162               Mewtwo       True
163  MewtwoMega Mewtwo X       True
..                   ...        ...
795              Diancie       True
796  DiancieMega Diancie       True
797  HoopaHoopa Confined       True
798   HoopaHoopa Unbound       True
799            Volcanion       True

[65 rows x 2 columns]

Select all Pokémon that are Generation 1 AND Legendary.

In [42]:
# put your answer here
df.loc[(df["Generation"] == 1) & (df["Legendary"] == True), ["Name", "Generation", "Legendary"]]

                    Name  Generation  Legendary
156             Articuno           1       True
157               Zapdos           1       True
158              Moltres           1       True
162               Mewtwo           1       True
163  MewtwoMega Mewtwo X           1       True
164  MewtwoMega Mewtwo Y           1       True

Select all Pokémon that are Water type OR Grass type.

In [45]:
# put your answer here
df.loc[(df["Type 1"] == "Water") | (df["Type 1"] == "Grass") & (df["Type 2"] == "Water") | (df["Type 2"] == "Grass"), ["Name", "Type 1", "Type 2"]]

                        Name Type 1 Type 2
9                   Squirtle  Water    NaN
10                 Wartortle  Water    NaN
11                 Blastoise  Water    NaN
12   BlastoiseMega Blastoise  Water    NaN
51                     Paras    Bug  Grass
..                       ...    ...    ...
783      PumpkabooSuper Size  Ghost  Grass
784    GourgeistAverage Size  Ghost  Grass
785      GourgeistSmall Size  Ghost  Grass
786      GourgeistLarge Size  Ghost  Grass
787      GourgeistSuper Size  Ghost  Grass

[134 rows x 3 columns]

Select all Pokémon that are Fire type AND Attack > 120.

In [48]:
# put your answer here
df.loc[(df["Type 1"] == "Fire") & (df["Attack"] > 120) | (df["Type 2"] == "Fire") & (df["Attack"] > 120), ["Name", "Type 1", "Type 2", "Attack"]]

                          Name  Type 1    Type 2  Attack
7    CharizardMega Charizard X    Fire    Dragon     130
147                    Flareon    Fire       NaN     130
270                      Ho-oh    Fire    Flying     130
279      BlazikenMega Blaziken    Fire  Fighting     160
424      GroudonPrimal Groudon  Ground      Fire     180
559                     Emboar    Fire  Fighting     123
615    DarmanitanStandard Mode    Fire       NaN     140

Select all Pokémon whose type is in this list:
`["Dragon", "Ghost", "Dark"]`.

In [52]:
# put your answer here
pokemon_types = ["Dragon", "Ghost", "Dark"]
df.loc[(df["Type 1"].isin(pokemon_types)) | (df["Type 2"].isin(pokemon_types)), ["Name", "Type 1", "Type 2"]]

                          Name   Type 1  Type 2
7    CharizardMega Charizard X     Fire  Dragon
99                      Gastly    Ghost  Poison
100                    Haunter    Ghost  Poison
101                     Gengar    Ghost  Poison
102          GengarMega Gengar    Ghost  Poison
..                         ...      ...     ...
791                    Noivern   Flying  Dragon
793                    Yveltal     Dark  Flying
794           Zygarde50% Forme   Dragon  Ground
797        HoopaHoopa Confined  Psychic   Ghost
798         HoopaHoopa Unbound  Psychic    Dark

[139 rows x 3 columns]

## 4. Categorical Exploration `(9 pts)`

Find the number of Pokémon per primary type.

In [53]:
# put your answer here
df["Type 1"].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

Find the number of Pokémon per generation.

In [54]:
# put your answer here
df["Generation"].value_counts()

Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64

Which type appears the most? Which appears the least?

In [61]:
# put your answer here
print(f"type that appears the most: {df["Type 1"].value_counts().idxmax()}")
print(f"type that apeears the least: {df["Type 1"].value_counts().idxmin()}")

type that appears the most: Water
type that apeears the least: Flying

How many unique primary types (Type 1) exist?

In [65]:
# put your answer here
df["Type 1"].nunique()

18

How many unique secondary types (Type 2) exist?

In [66]:
# put your answer here
df["Type 2"].nunique()

18


Which primary types have the most dual-type combinations?

In [81]:
# put your answer here  --checking dual types
df_dual_type = df[df['Type 2'].notnull()]
df_dual_type.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False

In [86]:
# checking value counts for each type in primary
df_dual_type['Type 1'].value_counts()

Type 1
Water       53
Bug         52
Normal      37
Grass       37
Rock        35
Fire        24
Ghost       22
Steel       22
Dragon      21
Dark        21
Ground      19
Psychic     19
Electric    17
Poison      13
Ice         11
Fighting     7
Fairy        2
Flying       2
Name: count, dtype: int64

In [87]:
# answer
most_dual_type_primary_type = unique_dual_type_counts.idxmax()
print(f"The primary type with the most dual-type combination is: {most_dual_type_primary_type}")

The primary type with the most dual-type combination is: Water

Which type has the highest mean Attack?

In [91]:
# put your answer here
df.groupby("Type 1")["Attack"].mean().idxmax()

'Dragon'

Which type has the lowest mean Defense?

In [92]:
# put your answer here
df.groupby("Type 1")["Defense"].mean().idxmin()

'Normal'


Which generation has the highest average Speed?

In [100]:
# put your answer here
print(f"Generation with the highest average Speed: {df.groupby('Generation')['Speed'].mean().idxmax()}")

Generation with the highest average Speed: 1

## 5. Groupby & Aggregation `(13 pts)`

Compute the average Attack per primary type.

In [102]:
# put your answer here
df.groupby("Type 1")["Attack"].mean()

Type 1
Bug          70.971014
Dark         88.387097
Dragon      112.125000
Electric     69.090909
Fairy        61.529412
Fighting     96.777778
Fire         84.769231
Flying       78.750000
Ghost        73.781250
Grass        73.214286
Ground       95.750000
Ice          72.750000
Normal       73.469388
Poison       74.678571
Psychic      71.456140
Rock         92.863636
Steel        92.703704
Water        74.151786
Name: Attack, dtype: float64

Compute the maximum HP per generation.

In [103]:
# put your answer here
df.groupby("Generation")["HP"].max()

Generation
1    250
2    255
3    170
4    150
5    165
6    126
Name: HP, dtype: int64

Compute the total number of Pokémon per primary type.

In [105]:
# put your answer here
df["Type 1"].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

For each type, compute:

- mean Attack

- mean Defense

- mean Speed

In [114]:
# put your answer here
print("Mean stats grouped by Type 1:")
print(df.groupby("Type 1")[["Attack", "Defense", "Speed"]].mean())
print("\nMean stats grouped by Type 2:")
print(df.groupby("Type 2")[["Attack", "Defense", "Speed"]].mean())

Mean stats grouped by Type 1:
              Attack     Defense       Speed
Type 1
Bug        70.971014   70.724638   61.681159
Dark       88.387097   70.225806   76.161290
Dragon    112.125000   86.375000   83.031250
Electric   69.090909   66.295455   84.500000
Fairy      61.529412   65.705882   48.588235
Fighting   96.777778   65.925926   66.074074
Fire       84.769231   67.769231   74.442308
Flying     78.750000   66.250000  102.500000
Ghost      73.781250   81.187500   64.343750
Grass      73.214286   70.800000   61.928571
Ground     95.750000   84.843750   63.906250
Ice        72.750000   71.416667   63.458333
Normal     73.469388   59.846939   71.551020
Poison     74.678571   68.821429   63.571429
Psychic    71.456140   67.684211   81.491228
Rock       92.863636  100.795455   55.909091
Steel      92.703704  126.370370   55.259259
Water      74.151786   72.946429   65.964286

Mean stats grouped by Type 2:
              Attack     Defense      Speed
Type 2
Bug        90.000000   80.000000  61.666667
Dark      109.800000   72.050000  75.350000
Dragon     94.444444   87.055556  80.555556
Electric   72.666667   68.333333  71.500000
Fairy      61.608696   73.869565  61.217391
Fighting  112.846154   82.500000  87.384615
Fire       81.250000   80.166667  79.666667
Flying     80.288660   68.309278  85.721649
Ghost      84.142857   82.285714  53.857143
Grass      74.160000   80.120000  57.320000
Ground     89.857143   90.314286  54.657143
Ice        98.000000   85.642857  74.642857
Normal     52.750000   53.750000  89.250000
Poison     67.588235   59.558824  66.647059
Psychic    74.696970   87.030303  69.484848
Rock       84.000000  126.857143  36.000000
Steel      92.590909  104.636364  59.363636
Water      70.142857   85.071429  57.142857

For each generation, compute:

- count

- mean Total

- number of Legendary Pokémon (hint: use sum on Boolean)

In [119]:
# put your answer here
df.groupby("Generation").agg(
    Count=('Name', 'count'),
    Total_Mean=('Total', 'mean'),
    Legendary_Count=('Legendary', 'sum')
)

            Count  Total_Mean  Legendary_Count
Generation
1             166  426.813253                6
2             106  418.283019                5
3             160  436.225000               18
4             121  459.016529               13
5             165  434.987879               15
6              82  436.378049                8

Which type combination (Type 1 + Type 2) has the highest average Attack?

In [120]:
# put your answer here
df.groupby(["Type 1", "Type 2"])["Attack"].mean().idxmax()

('Ground', 'Fire')

Which generation has the highest proportion of Legendary Pokémon?

In [122]:
# put your answer here
print(f"Generation with the highest Legendary Pokemon proportion: {df.groupby("Generation")["Legendary"].mean().idxmax()}")

Generation with the highest Legendary Pokemon proportion: 3


Which primary type has the largest variance in HP?

In [123]:
# put your answer here
df.groupby("Type 1")["HP"].var().idxmax()

'Normal'

Which primary type has the highest median Speed?

In [124]:
# put your answer here
df.groupby("Type 1")["Speed"].median().idxmax()

'Flying'

Group Pokémon by whether they are Legendary or not. Compare:

- mean Total

- mean Attack

- mean Defense

- mean Speed

In [125]:
# put your answer here
df.groupby("Legendary")[["Total", "Attack", "Defense", "Speed"]].mean()

                Total      Attack    Defense       Speed
Legendary
False      417.213605   75.669388  71.559184   65.455782
True       637.384615  116.676923  99.661538  100.184615

Show the top 5 strongest types by mean Total.

In [126]:
# put your answer here
df.groupby("Type 1")["Total"].mean().nlargest(5)

Type 1
Dragon     550.531250
Steel      487.703704
Flying     485.000000
Psychic    475.947368
Fire       458.076923
Name: Total, dtype: float64

Rank generations by their average Attack.

In [127]:
# put your answer here
df.groupby("Generation")["Attack"].mean().rank(ascending=False)

Generation
1    4.0
2    6.0
3    3.0
4    1.0
5    2.0
6    5.0
Name: Attack, dtype: float64

Show the top 10 fastest Pokémon using nlargest(10, "Speed").

In [134]:
# put your answer here
df.nlargest(10, "Speed")

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
431,386,DeoxysSpeed Forme,Psychic,NaN,600,50,95,90,95,90,180,3,True
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
428,386,DeoxysNormal Forme,Psychic,NaN,600,50,150,50,150,50,150,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
275,254,SceptileMega Sceptile,Grass,Dragon,630,70,110,75,145,85,145,3,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
109,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,False